FROM ubuntu:xenial
MAINTAINER Sebin Benjamin <sebinbenjamin@gmail.com>

# expose the port
EXPOSE 8080

# default jenkins home directory
ENV JENKINS_HOME /var/jenkins

# set our user home to the same location
ENV HOME /var/jenkins

# for installing openjdk
RUN apt-get update -qq && apt-get install -qqy openjdk-8-jdk  wget curl git iptables ca-certificates apparmor

# for jenkins     
RUN echo deb https://pkg.jenkins.io/debian-stable binary/ >> /etc/apt/sources.list \
	&& wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -

RUN apt-get update -qq && apt-get install -qqy jenkins 

# default command to launch jenkins. specify the JAVA_OPTIONS variable using the “-e” switch.
CMD java -XX:+PrintFlagsFinal -XX:+PrintGCDetails $JAVA_OPTIONS -jar /usr/share/jenkins/jenkins.war
